/*!
 * cloudpipe — serverless Cloudflare tunnels for Node.js.
 *
 * Generated by hand because the napi-rs auto-generator doesn't model
 * the per-event callback shape (each event variant maps to its own
 * camelCase event name with a different payload object). The shape is
 * kept in sync with `crates/cloudpipe-node/src/event.rs`.
 */

export interface ConnectOptions {
  /** Cloudflare API token. Required. */
  token: string;

  /**
   * Base domain (e.g. `example.com`). Optional when the token has
   * access to exactly one zone — the SDK will auto-discover the zone.
   */
  domain?: string;

  /**
   * Local service protocol. One of `"http"`, `"https"`, `"tcp"`,
   * `"udp"`, `"ssh"`. Defaults to `"http"`.
   */
  protocol?: 'http' | 'https' | 'tcp' | 'udp' | 'ssh';

  /** Local port to expose. Defaults to `8080`. */
  port?: number;

  /**
   * Desired subdomain. If omitted or empty, a random one is generated
   * by the SDK.
   */
  subdomain?: string;

  /**
   * When `true`, the SDK automatically respawns `cloudflared` on the
   * same public URL if it crashes. Defaults to `false`.
   */
  autoRestart?: boolean;

  /**
   * Path to a pre-installed `cloudflared` binary. When omitted, the
   * SDK searches `PATH`, then falls back to `~/.cfp/bin/cloudflared`,
   * then downloads from GitHub releases (with the configured mirror).
   */
  cloudflaredPath?: string;

  /**
   * Override the GitHub mirror prefix used when downloading
   * `cloudflared`. Pass an empty string to disable mirroring.
   */
  githubProxy?: string;
}

/** Opens a new tunnel and returns a `Listener` handle. */
export declare function connect(options: ConnectOptions): Promise<Listener>;

/** Library version, mirrored from `Cargo.toml`. */
export declare function version(): string;

/** All event names the SDK may emit. */
export type ListenerEventName =
  | 'banner'
  | 'resolvingConflicts'
  | 'creatingTunnel'
  | 'ingressConfigured'
  | 'dnsCreated'
  | 'cloudflaredStarted'
  | 'restarting'
  | 'restarted'
  | 'restartGivingUp'
  | 'edgeConnected'
  | 'cloudflaredLog'
  | 'shuttingDown'
  | 'cleaned';

/** Severity level attached to a `cloudflaredLog` event. */
export type LogLevel = 'info' | 'warn' | 'error';

/**
 * `reason` payload on `restarting` and `shuttingDown` events. Forward
 * compatibility: any unrecognized variant comes through as
 * `{ kind: 'other', debug: '<Debug form>' }`.
 */
export type ShutdownReason =
  | { kind: 'userRequested' }
  | { kind: 'childExited' }
  | { kind: 'error'; message: string }
  | { kind: 'other'; debug: string };

/** Per-event payload shapes. Keys match {@link ListenerEventName}. */
export interface ListenerEventPayloadMap {
  banner: Record<string, never>;
  resolvingConflicts: Record<string, never>;
  creatingTunnel: { name: string };
  ingressConfigured: { protocol: string; port: number };
  dnsCreated: { fullName: string };
  cloudflaredStarted: Record<string, never>;
  restarting: { reason: ShutdownReason; attempt: number };
  restarted: { attempt: number };
  restartGivingUp: { attempts: number; lastError: string };
  edgeConnected: { connIndex: number; total: number };
  cloudflaredLog: { level: LogLevel; line: string };
  shuttingDown: { reason: ShutdownReason };
  cleaned: Record<string, never>;
}

/** A live Cloudflare tunnel. Constructed via {@link connect}. */
export declare class Listener {
  /** The full public URL of the tunnel (always HTTPS). */
  readonly url: string;

  /** The public hostname (`myapp.example.com`). */
  readonly fullName: string;

  /** Just the subdomain part (`myapp`). */
  readonly subdomain: string;

  /**
   * Registers a callback for a single named event. The callback
   * receives the event payload as a JSON string — `JSON.parse` it
   * inside the handler to access fields.
   *
   * Example:
   *
   * ```ts
   * listener.on('creatingTunnel', (json) => {
   *   const { name } = JSON.parse(json);
   *   console.log('creating tunnel', name);
   * });
   * ```
   */
  on(event: ListenerEventName, callback: (payload: string) => void): void;

  /**
   * Blocks until the tunnel exits on its own (cloudflared crashed,
   * auto-restart exhausted, etc.). With auto-restart enabled this only
   * returns after `close()` has run.
   */
  wait(): Promise<void>;

  /**
   * Triggers a clean shutdown and waits for it to complete. Idempotent:
   * calling twice surfaces an `ALREADY_SHUT_DOWN` error.
   */
  close(): Promise<void>;
}

/**
 * Cloudpipe error codes. The JS side surfaces them as a `[CODE]` prefix
 * on `error.message` — JS callers should split the prefix off the
 * front before falling through to the underlying SDK message.
 */
export type CloudpipeErrorCode =
  | 'MISSING_CREDENTIAL'
  | 'CLOUDFLARE_API'
  | 'CLOUDFLARE_BINARY'
  | 'INVALID_SUBDOMAIN'
  | 'SUBDOMAIN_IN_USE'
  | 'ALREADY_SHUT_DOWN'
  | 'IO'
  | 'OTHER';

/**
 * Extracts the `[CODE]` prefix from a cloudpipe error message. Useful
 * when you need to branch on the typed cause without parsing the rest.
 *
 * ```ts
 * try {
 *   await connect({ token });
 * } catch catch (e: any) {
 *   const code = parseErrorCode(e.message);
 *   if (code === 'CLOUDFLARE_API') ...
 * }
 * ```
 */
export function parseErrorCode(message: string): CloudpipeErrorCode | null;